title: Cookie Thief
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A Node.js framework for extracting cookies from a browser installed on your system.
baseurl: "/cookie-thief" # the subpath of your site, e.g. /blog
url: "https://kalininator.github.io" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: just-the-docs/just-the-docs
theme: "just-the-docs"

# logo: "https://tray.io/favicon-32x32.png"

color_scheme: light

back_to_top: true
back_to_top_text: "Back to top"

search:
  heading_level: 3
  button: true

aux_links:
  "Cookie Thief on GitHub":
    - "//github.com/kalininator/cookie-thief"
